### ISSUE TITLE
Two different behaviors at a different position of the callback function

### ISSUE THREAD

**Issue by fizikst** [BigAB/use-epic#11]
**First behavior**

[Callback function "handleChangeRTT" defined inside react function App](https://codesandbox.io/s/epic-ardinghelli-6okrp)  - timer completed after the first loop.

**Second behavior**

[Callback function "handleChangeRTT" defined outside react function App](https://codesandbox.io/s/cool-wu-nwh9v) - timer completed as per condition.

What is the option ?

**Comment by BigAB** [comment]
So the problem come from the fact that the `deps` value of `handleChangeRTT` is changing every time the component renders.

Because of that the observable is unsubscribed  from immediately after re-rendering because of the first state change (`undefined` -> `0`).

The options you have:
  - like you have above, define the dependancy outside of the component so that the reference to the function remains constant.
  - use either `useMemo` or `useCallback` to keep the reference to the `handleChangeRTT` constant

```js
  const handleChangeRTT = useCallback(() => console.log("test"), []);
  const [index, dispatch] = useEpic(timerEpic, { deps: { handleChangeRTT } });
```

**Comment by fizikst** [comment]
Thanks for the answer.
